"""+ column activity_tree for better org info read

Revision ID: b99b880c3395
Revises: 5d9aca844a32
Create Date: 2025-08-07 21:16:08.296747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b99b880c3395"
down_revision: Union[str, Sequence[str], None] = "5d9aca844a32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "activity_tree", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "activity_tree")
    # ### end Alembic commands ###
